### PR TITLE
Add a default config option

### PR DESCRIPTION
**Pull request by senthilp**

### CODE REVIEW

**Comment by merwan7** [comment]
:+1: Will publish to npm asap.  Thanks, Senthil!

**Comment by senthilp** [comment]
Thanks @merwan7 Is it also published

**Comment by merwan7** [comment]
All set!

```
~/git/lasso-autoprefixer ~> npm view lasso-autoprefixer

{ name: 'lasso-autoprefixer',
  description: 'Autoprefixer plugin for Lasso.js using postcss & autoprefixer-core',
  'dist-tags': { latest: '1.0.2' },...
```

**Comment by senthilp** [comment]
Thanks a lot.

**Pull request merged**
