### PR TITLE
autoprefixer update

### PR DESCRIPTION
**Pull request by kuznetsov-online**

### CODE REVIEW

**Comment by austinkelleher** [comment]
Hey @FiW thanks for the PR. Why did you remove `postcss` as a dependency? It's still used in `lasso-prefixer.js`. Should it be a peerDependency?

**Comment by kuznetsov-online** [comment]
postcss is dependency of  **autoprefixer**

**Comment by austinkelleher** [comment]
@FiW I see that it's a dependency of autoprefixer, but still if you're using an npm 2 or below (automatically packaged with Node.js 4), then `postcss` will be a nested dependency of `autoprefixer` in the `node_modules` folder, which means it will not be available inside of `lasso-autoprefixer`. I think we need to add back `postcss` and upgrade it to the latest version. Thoughts?

**Comment by kuznetsov-online** [comment]
yeah, you are right

**Comment by austinkelleher** [comment]
A major version was required since autoprefixer 7 dropped support for Node < 4. Published `lasso-prefixer@3.0.0` with your change. Thanks a lot for your help on these modules. Much appreciated. 👍

**Pull request merged**
